---
title: "Guidelines and Project Memo"
author: "Safiya Alavi and Maya Sinha"
date: "10/8/2022"
output: html_document
---
## Guidelines
#### Code
Uses the tidyverse and tidymodels for fitting
models, etc. includes comments as necessary.
Uses code folding so huge blocks of code
aren't displayed when knitting.

#### Narration
Includes introduction and conclusion sections.
Good flow of text and narration throughout; at
least some description/explanation for every
piece of code/results. Easily readable. Makes
an effort to explain/make sense to general
audience. Written like a paper. Divided into
reasonable sections.

#### Exploratory Data Analysis
Conducts some EDA. Explores outcome
variable distribution. Assesses missing data
patterns. Creates at least 3-5 plots or tables to
explore relationships among variables.

#### Organization and Structure
Submits a link to a GitHub repository
containing your project, with .Rmd and knitted
.html or .pdf. Includes at least one subfolder
for data (with subdirectories). Includes
codebook and data citation.

#### Feature Extraction
Creates appropriate models. Handles
categorical predictors reasonably (with
dummy/one-hot encoding, PCA, etc.). Creates
interactions if necessary. Justifies any variable
transformations.

#### Data Splitting
Divides data into training and test sets with a
reasonable proportion. Uses stratified
sampling. Uses cross-validation to fold
training set. (Ideally, stratified CV with
repeats.)

#### Model Fitting
Fits at least 4 model classes (random forest,
KNN, boosted tree, lasso or ridge regression or
logistic regression, SVM, neural network).
Tunes models across resamples. Fits optimal
tuned model to training and test sets.